_target_: uni2ts.data.builder.ConcatDatasetBuilder
_args_:
  _target_: uni2ts.data.builder.simple.generate_eval_builders
  dataset: customdataset_eval
  offset: 12442
  eval_length: 3110
  prediction_lengths: [3100]
  context_lengths: [12, 24, 48, 96, 192, 384, 768, 1536]
  patch_sizes: [32, 64, 128]